spring:
  application:
    name: provider
dubbo:
  scan:
    base-packages: com.test.provider.service
  protocol:
    name: dubbo
    port: -1

  registry:
    address: zookeeper://127.0.0.1:2181
    file: ./dubbo.cache

demo:
  service:
    version: 1.0.0